In [1]:
###aaaa

In [2]:
### %run

In [3]:
def hello(name):
    print('hello', name)
hello("Tim")

hello Tim


In [4]:
%run hello.py

ERROR:root:File `'hello.py'` not found.


## timeit

In [6]:
%timeit L = [i**2 for i in range(1000000)]

293 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit L = [i**2 for i in range(100)]

26.3 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%time L = [i**2 for i in range(100)]

CPU times: user 40 µs, sys: 1e+03 ns, total: 41 µs
Wall time: 42.9 µs


In [7]:
%timeit L = [i**2 for i in range(100)]

26.3 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## hhh

In [8]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

319 µs ± 6.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%%time
L = []
for n in range(1000):
    L.append(n**2)

CPU times: user 471 µs, sys: 1e+03 ns, total: 472 µs
Wall time: 474 µs


In [12]:
import random
L = [random.random() for i in range(1000)]

In [14]:
%%timeit L.sort()

UsageError: %%timeit is a cell magic, but the cell body is empty. Did you mean the line magic %timeit (single %)?


In [15]:
%timeit L.sort()

2.93 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit L.sort()

2.82 µs ± 76.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [18]:
%ls

Applications/      Library/           Pictures/          miniconda3/
Desktop/           ML Learning.ipynb  Public/            wekafiles/
Documents/         Movies/            Snapshots/
Downloads/         Music/             eclipse/


In [19]:
%run?

In [20]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [21]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [22]:
import numpy as np


ModuleNotFoundError: No module named 'numpy'

In [4]:
n = 10
L = [i for i in range(n)]

In [5]:
L * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
%%time
A = []
for e in L:
    A.append(3*e)

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 7.87 µs


In [9]:
%%time
[e*2 for e in L]

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
import numpy as np
L = np.arange(10)

In [12]:
%%time
A = np.array([e*2 for e in L])

CPU times: user 174 µs, sys: 177 µs, total: 351 µs
Wall time: 5.5 ms


In [13]:
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
L /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [15]:
L**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
X = np.arange(15).reshape((3, 5))

In [17]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [19]:
X + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
X // 2

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7]])

In [21]:
X % 2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [22]:
1 / X

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857]])

In [23]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [24]:
np.cos(X)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [25]:
np.abs(X)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [29]:
3**X

array([[      1,       3,       9,      27,      81],
       [    243,     729,    2187,    6561,   19683],
       [  59049,  177147,  531441, 1594323, 4782969]])

In [28]:
np.power(3, X)

array([[      1,       3,       9,      27,      81],
       [    243,     729,    2187,    6561,   19683],
       [  59049,  177147,  531441, 1594323, 4782969]])

In [30]:
X.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
np.log(X)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [32]:
np.log2(X)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ],
       [3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492]])

In [35]:
D = np.full((2,3), 5)

In [34]:
C = np.full((3,2), 3)

In [36]:
C + D

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [37]:
C * D

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [38]:
C.dot(D)

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [39]:
C / D

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [40]:
z = np.array([1,2,3])

In [41]:
z + D

array([[6, 7, 8],
       [6, 7, 8]])

In [42]:
z + C

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [43]:
z

array([1, 2, 3])

In [44]:
D

array([[5, 5, 5],
       [5, 5, 5]])

In [45]:
np.tile(z, (2, 1))

array([[1, 2, 3],
       [1, 2, 3]])

In [46]:
np.tile(z, (2, 1)) + D

array([[6, 7, 8],
       [6, 7, 8]])

In [47]:
z + D

array([[6, 7, 8],
       [6, 7, 8]])

In [48]:
z * D

array([[ 5, 10, 15],
       [ 5, 10, 15]])

In [50]:
z.dot(C)

array([18, 18])

In [51]:
D.dot(z)

array([30, 30])

In [61]:
np.linalg.inv(z)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [62]:
G = np.full((3,3), 7)

In [63]:
G

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [64]:
np.linalg.inv(G)

LinAlgError: Singular matrix

In [65]:
F = np.array([[2,3],[7,1]])

In [66]:
F

array([[2, 3],
       [7, 1]])

In [69]:
Fi = np.linalg.inv(F)

In [68]:
F.dot(np.linalg.inv(F))

array([[ 1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [70]:
Fi.dot(F)

array([[ 1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [71]:
np.linalg.inv(C)

LinAlgError: Last 2 dimensions of the array must be square

In [73]:
Cpinv = np.linalg.pinv(C)

In [74]:
Cpinv.shape

(2, 3)

In [75]:
C.dot(Cpinv)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [78]:
np.random.random(100)

array([0.95944315, 0.99502984, 0.59030835, 0.77771632, 0.8553504 ,
       0.30416639, 0.0797411 , 0.28929655, 0.79047218, 0.89544429,
       0.19840844, 0.58410905, 0.74955929, 0.82455914, 0.44102481,
       0.18774187, 0.7228848 , 0.76217141, 0.38572306, 0.03394969,
       0.65797713, 0.91640172, 0.41421869, 0.70662219, 0.62531206,
       0.51198929, 0.42609314, 0.78004531, 0.39174167, 0.79952842,
       0.25850859, 0.90446916, 0.88333445, 0.93173217, 0.06432253,
       0.72165362, 0.11206025, 0.46392505, 0.91266267, 0.43630992,
       0.97791439, 0.81380682, 0.49238637, 0.01905233, 0.35572775,
       0.59449446, 0.60059094, 0.06718285, 0.95790961, 0.87690147,
       0.97567973, 0.44281362, 0.69247453, 0.69795644, 0.96678046,
       0.70810696, 0.74386479, 0.58022076, 0.36535259, 0.32605963,
       0.61243645, 0.38737545, 0.98291337, 0.63153805, 0.04993867,
       0.81419967, 0.6864425 , 0.83780664, 0.66878218, 0.60139153,
       0.11951224, 0.59293753, 0.41992762, 0.02503936, 0.31940

In [79]:
R = np.random.random(100)

In [80]:
R

array([0.93853827, 0.6440625 , 0.4434744 , 0.61617548, 0.05853897,
       0.83851699, 0.38769516, 0.67676244, 0.74546549, 0.65540147,
       0.23771476, 0.2990328 , 0.35615388, 0.76576687, 0.64010861,
       0.01955811, 0.22244715, 0.99258187, 0.31853597, 0.07788123,
       0.95098629, 0.76685986, 0.12482914, 0.85811755, 0.53730276,
       0.94629254, 0.74962127, 0.95580703, 0.43833348, 0.77128974,
       0.78436503, 0.16784053, 0.59033659, 0.97427993, 0.44876278,
       0.17614124, 0.57939457, 0.73544858, 0.38027555, 0.24677858,
       0.64251999, 0.05526944, 0.03055171, 0.55638059, 0.18390747,
       0.17767795, 0.15500951, 0.52927127, 0.33873379, 0.44483598,
       0.51524121, 0.29409773, 0.02113589, 0.49312541, 0.87415084,
       0.46561246, 0.35876275, 0.98276218, 0.99837695, 0.44132333,
       0.03088159, 0.93697785, 0.59903422, 0.22970317, 0.70270441,
       0.47786173, 0.82813856, 0.27239146, 0.70352447, 0.21814117,
       0.11839488, 0.00629438, 0.97696895, 0.14952145, 0.91645

In [81]:
np.sum(R)

48.29964653784742

In [83]:
R.sum()

48.29964653784742

In [86]:
%%time
np.sum(R)
R.sum()

CPU times: user 48 µs, sys: 4 µs, total: 52 µs
Wall time: 55.1 µs


In [87]:
H = np.arange(100).reshape((10, 10))

In [88]:
np.mean(H)

49.5

In [89]:
np.median(H)

49.5

In [90]:
np.sum(H, axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [91]:
np.sum(H, axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [92]:
H

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
np.prod(H+1)

0

In [95]:
H+1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [100]:
np.percentile(H, q=50)

49.5

In [99]:
np.median(H)

49.5

In [101]:
np.percentile(H, q=100)

99.0

In [102]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(H, percent))

0.0
24.75
49.5
74.25
99.0


In [103]:
np.var(H)

833.25

In [104]:
np.std(H)

28.86607004772212

In [105]:
s = np.random.normal(0, 1, size=1000)

In [106]:
s

array([ 1.27122565e+00,  5.97664283e-02,  6.89736585e-01,  2.40810286e-01,
        4.92770300e-01,  5.16411470e-01,  1.12244939e+00,  1.18916351e+00,
        3.95817221e-02, -2.15350066e-01,  1.78979219e-02,  1.04034041e+00,
       -1.58929602e+00, -8.88526422e-02, -9.50453287e-01,  1.12040468e+00,
       -1.29272001e+00,  1.13376895e+00,  5.42290773e-01, -4.14173924e-01,
        2.80059708e-01, -9.48128496e-01,  1.52446570e-01,  7.65979648e-02,
       -9.87252024e-01, -1.25910481e+00,  6.83720554e-01,  9.85215174e-01,
       -3.68430331e-01, -2.13018529e-01, -4.19777579e-01,  2.68708817e-01,
        1.74734795e+00,  6.80145405e-01,  1.77058473e+00,  4.74979691e-01,
       -6.90478333e-01,  7.35552332e-02, -9.20077529e-01,  6.10349707e-01,
        1.41626092e-01, -6.17960370e-01,  2.19804477e-01, -1.03082451e+00,
        9.01985418e-01, -5.10639105e-01,  1.92090030e-01,  6.75745070e-01,
       -2.50056218e+00, -5.67284723e-01, -1.08861295e-01,  1.22739316e+00,
        1.06997266e+00,  

In [107]:
np.mean(s)

0.03881818580058934

In [108]:
np.std(s)

0.9910259795579579