In [73]:
import numpy as np

In [74]:
np.array([1,2,3])

array([1, 2, 3])

In [75]:
L = np.array([1,2,3])

In [76]:
L.dtype

dtype('int64')

In [77]:
L[2] = ''

ValueError: invalid literal for int() with base 10: ''

In [ ]:
L[1] = 1.2222

In [ ]:
L

In [ ]:
np.zeros(10, dtype='int')

In [ ]:
np.ones(10, dtype='int')

In [ ]:
np.full((2,3), 2,dtype='int')

In [ ]:
np.full((5,3), 2,dtype='int')

In [ ]:
[i for i in range(10)]

In [ ]:
np.arange(0, 10, 2)

In [ ]:
np.linspace(0, 10, 5)

In [ ]:
np.random.randint(4,8, size=(3, 7))

In [ ]:
np.random.seed(66)
np.random.randint(0, 10)

In [ ]:
np.random.random((2,3))

In [ ]:
np.random.normal(0,1,(2,3))

In [ ]:
np.random.normal(1, 200, (2,3))

In [ ]:
np.random.normal?

In [ ]:
help(np.random)

###props

In [ ]:
x = np.arange(10)

In [ ]:
X= np.arange(15).reshape(3,5)

In [ ]:
X

In [ ]:
x[1]

In [ ]:
X[:2]

In [ ]:
X[2][3]

In [ ]:
X[2:3]

In [ ]:
X[2,3]

In [ ]:
x[:3]

In [78]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [79]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [80]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [84]:
X[0]

array([0, 1, 2, 3, 4])

In [85]:
X[0].ndim

1

In [86]:
X[0, :].ndim

1

In [87]:
X[:, 0]

array([ 0,  5, 10])

In [88]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
X.shape

(3, 5)

In [90]:
np.full((2,3), 2,dtype='int')

array([[2, 2, 2],
       [2, 2, 2]])

In [91]:
X.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
np.full((2,3), 2,dtype='int')

array([[2, 2, 2],
       [2, 2, 2]])

In [93]:
np.full((2,3), 2,dtype='int')

array([[2, 2, 2],
       [2, 2, 2]])

In [94]:
X.reshape(-1, 15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [95]:
y = x

In [96]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
y = x.copy()

In [98]:
y


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
A = np.array([[1,2,3],[7,7,7]])

In [111]:
B = np.array([[4,5,6]])

In [100]:
A

array([1, 2, 3])

In [114]:
np.concatenate([A,B], axis=0)

array([[1, 2, 3],
       [7, 7, 7],
       [4, 5, 6]])

In [116]:
np.array(2,3)

TypeError: data type not understood

In [126]:
A = np.arange(15).reshape((5, 3))

In [130]:
A.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [131]:
B.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [125]:
B = np.arange(20).reshape((4, 5))

In [133]:
np.concatenate([A.reshape(1,-1),B.reshape(1,-1)], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,
         1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]])

In [137]:
np.vstack([A.reshape(1,-1),B])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [138]:
np.vstack([A])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [139]:
C= np.arange(10).reshape(5,2)

In [140]:
C


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [143]:
v1,v2,v3 = np.split(C, [2, 3])

In [144]:
v1

array([[0, 1],
       [2, 3]])

In [145]:
v2

array([[4, 5]])

## A = np.arange(15).reshape((5, 3))

In [146]:
v3

array([[6, 7],
       [8, 9]])

In [147]:
A.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [148]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [149]:
s, r = np.hsplit(A, [-1])

In [150]:
s

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [151]:
r

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [152]:
r.reshape([:, 1])

SyntaxError: invalid syntax (<ipython-input-152-7e34d59db2c3>, line 1)

In [153]:
r[:,0]

array([ 2,  5,  8, 11, 14])